.PHONY: dev build install

dev:
	@pnpm run dev

build:
	@pnpm run build

install:
	@pnpm install

install-libs:
	@pnpm install --save-dev \
		react \
		react-dom \
		react-router \
		vite \
		typescript \
		tailwindcss \
		@vitejs/plugin-react \
		@tailwindcss/vite \
		@tailwindcss/postcss \
		@types/node \
		@types/react \
		@types/react-dom
